apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.secretName }}
  labels:
    {{- include "flaskapi.labels" . | nindent 4 }}
data:
  pguser: {{ default "" .Values.secret.dbuser | b64enc | quote }}
  pgpass: {{ default "" .Values.secret.dbpass | b64enc | quote }}