replicaCount: 1

image:
  repository: sanjanasaxena/titanic-flask-api:latest
  pullPolicy: IfNotPresent
  tag: latest

imagePullSecrets: []

nameOverride: ""

fullnameOverride: ""

secrets:
  secretName: pg_conn
  pguser: app
  pgpass: password

appProperties:
  env: development
  run_migrate: true

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 5000

ingress:
  enabled: true
  className: ""
  annotations: {}
  hosts:
    - host:
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources: {}

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
